language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=lint
  - TOXENV=docs
install:
  - pip install tox
script:
  - tox
sudo: false
matrix:
  allow_failures:
    - env: TOXENV=lint
    - env: TOXENV=docs
